# Generated by Django 6.0.4 on 2026-05-02 17:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('assignment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('invoicing_contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('ap_invoicing_contact', models.EmailField(blank=True, max_length=254, null=True)),
                ('title_from_client', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'db_table': 'Assignment',
            },
        ),
        migrations.CreateModel(
            name='BusinessDevelopment',
            fields=[
                ('business_development_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('no_status', 'No Status'), ('contact_made', 'Contact Made'), ('awaiting_csa_nda', 'Awaiting CSA/NDA'), ('csa_nda_signed', 'CSA/NDA Signed'), ('awaiting_projects', 'Awaiting Projects')], db_index=True, default='no_status', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=None, null=True)),
                ('date_converted', models.DateTimeField(default=None, null=True)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=20)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('work_orders', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('potential_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
            ],
            options={
                'db_table': 'BusinessDevelopment',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('client_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=20)),
                ('contract_date', models.DateField(blank=True, null=True)),
                ('work_orders', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Client',
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'Departments',
            },
        ),
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('industry_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'Industry',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='InteractionType',
            fields=[
                ('interation_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'db_table': 'InteractionType',
            },
        ),
        migrations.CreateModel(
            name='BillableRate',
            fields=[
                ('billable_rate_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billable_rates', to='railwayapp.assignment')),
            ],
            options={
                'db_table': 'BillableRate',
            },
        ),
        migrations.CreateModel(
            name='BusinessDevelopmentContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='railwayapp.businessdevelopment')),
            ],
            options={
                'db_table': 'BusinessDevelopmentContact',
            },
        ),
        migrations.CreateModel(
            name='ClientContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('is_notify_contact', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='railwayapp.client')),
            ],
            options={
                'db_table': 'ClientContact',
            },
        ),
        migrations.CreateModel(
            name='DocumentType',
            fields=[
                ('document_type_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('staff', 'Staff'), ('client', 'Client'), ('business_development', 'Business Development')], max_length=30)),
            ],
            options={
                'db_table': 'DocumentType',
                'ordering': ['name'],
                'unique_together': {('name', 'category')},
            },
        ),
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('blob_name', models.CharField(max_length=500, unique=True)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='railwayapp.client')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_client_documents', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_documents', to='railwayapp.documenttype')),
            ],
            options={
                'db_table': 'ClientDocument',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='BusinessDevelopmentDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('blob_name', models.CharField(max_length=500, unique=True)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('business_development', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='railwayapp.businessdevelopment')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_bd_documents', to=settings.AUTH_USER_MODEL)),
                ('document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='bd_documents', to='railwayapp.documenttype')),
            ],
            options={
                'db_table': 'BusinessDevelopmentDocument',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.AddField(
            model_name='client',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients', to='railwayapp.industry'),
        ),
        migrations.AddField(
            model_name='businessdevelopment',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_developments', to='railwayapp.industry'),
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], db_index=True, default='active', max_length=20)),
                ('work_orders', models.CharField(blank=True, null=True)),
                ('project_manager', models.CharField(max_length=200)),
                ('project_manager_email', models.EmailField(max_length=254)),
                ('effective_date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('reimbursable_expenses', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('reimbursable_expenses_notes', models.TextField(blank=True, null=True)),
                ('total_compensation', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('total_compensation_notes', models.TextField(blank=True, null=True)),
                ('invoice_attn', models.CharField(blank=True, max_length=200, null=True)),
                ('invoice_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='railwayapp.client')),
            ],
            options={
                'db_table': 'Projects',
            },
        ),
        migrations.AddField(
            model_name='assignment',
            name='project',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='railwayapp.project'),
        ),
        migrations.CreateModel(
            name='ProjectLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=255)),
                ('place_id', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='railwayapp.project')),
            ],
            options={
                'db_table': 'ProjectLocation',
            },
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('staff_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('date_entered', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('vetted', 'Vetted'), ('initial_contact', 'Initial Contact')], db_index=True, default='active', max_length=20)),
                ('employee_type', models.CharField(choices=[('contractor', 'Contractor'), ('full_time', 'Full Time'), ('part_time', 'Part Time')], db_index=True, default='contractor', max_length=20)),
                ('contractor_business_name', models.CharField(blank=True, max_length=255, null=True)),
                ('contractor_llc_role', models.CharField(blank=True, max_length=255, null=True)),
                ('rpr_manager', models.CharField(blank=True, max_length=255, null=True)),
                ('date_of_joining', models.DateField(blank=True, null=True)),
                ('rpr_contract_date', models.DateField(blank=True, null=True)),
                ('contractor_entered_into_adp', models.BooleanField(default=False)),
                ('contractor_paperwork_uploaded', models.BooleanField(default=False)),
                ('proof_of_insurance', models.BooleanField(default=False)),
                ('resume_on_file', models.BooleanField(default=False)),
                ('personal_email', models.EmailField(max_length=254, unique=True)),
                ('business_email', models.EmailField(default='notpopulated@fake.email', max_length=254)),
                ('street', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=2)),
                ('zip_code', models.CharField(max_length=20)),
                ('phone_number', models.CharField(max_length=20)),
                ('contract_status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('standby', 'Standby'), ('terminated', 'Terminated'), ('resigned', 'Resigned')], default='active', max_length=20)),
                ('contract_status_date', models.DateField(blank=True, null=True)),
                ('contract_status_reason', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('rpr_department', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='railwayapp.department')),
            ],
            options={
                'db_table': 'staffMember',
            },
        ),
        migrations.CreateModel(
            name='StaffDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_name', models.CharField(max_length=255)),
                ('blob_name', models.CharField(max_length=500, unique=True)),
                ('content_type', models.CharField(max_length=100)),
                ('file_size', models.PositiveIntegerField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('is_current', models.BooleanField(db_index=True, default=True)),
                ('is_archived', models.BooleanField(db_index=True, default=False)),
                ('document_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='staff_documents', to='railwayapp.documenttype')),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('staff_member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='railwayapp.staffmember')),
            ],
            options={
                'db_table': 'StaffDocument',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='PayRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('effective_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('staffMember', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pay_rates', to='railwayapp.staffmember')),
            ],
            options={
                'db_table': 'PayRate',
            },
        ),
        migrations.AddField(
            model_name='client',
            name='rpr_contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rpr_contacts', to='railwayapp.staffmember'),
        ),
        migrations.AddField(
            model_name='businessdevelopment',
            name='employee',
            field=models.ForeignKey(blank=True, limit_choices_to={'employee_type__in': ['full_time', 'part_time']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='business_developments', to='railwayapp.staffmember'),
        ),
        migrations.AddField(
            model_name='assignment',
            name='staff',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='railwayapp.staffmember'),
        ),
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveBigIntegerField()),
                ('date', models.DateTimeField(db_index=True)),
                ('comments', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='contenttypes.contenttype')),
                ('interaction_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interactions', to='railwayapp.interactiontype')),
            ],
            options={
                'db_table': 'Interaction',
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='Interaction_content_eba57f_idx'), models.Index(fields=['date'], name='Interaction_date_a72fb8_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='staffmember',
            index=models.Index(fields=['last_name', 'first_name'], name='staffMember_last_na_6bc137_idx'),
        ),
    ]
